import {cleanEvent} from './analytics-data.js';
const encode=encodeURIComponent;
const fieldsFor=event=>Object.fromEntries(Object.entries(event).map(([key,value])=>[key,typeof value==='boolean'?{booleanValue:value}:Number.isInteger(value)?{integerValue:String(value)}:{stringValue:value}]));
const readValue=value=>value?.stringValue??(value?.integerValue!==undefined?Number(value.integerValue):value?.booleanValue??value?.timestampValue??null);
export function firestoreEvent(document){return Object.fromEntries(Object.entries(document.fields||{}).map(([key,value])=>[key,readValue(value)]));}
export class FirebaseClient{
 constructor(config,{fetcher=globalThis.fetch}={}){this.config=config;this.fetcher=fetcher;this.session=null;}
 get configured(){return Boolean(this.config.apiKey&&this.config.projectId);}
 get documents(){return `https://firestore.googleapis.com/v1/projects/${encode(this.config.projectId)}/databases/(default)/documents`;}
 async json(url,options={}){const response=await this.fetcher(url,options);const result=await response.json().catch(()=>({}));if(!response.ok)throw Error(result.error?.message||`Firebase ${response.status}`);return result;}
 async signInAnonymously(){const result=await this.json(`https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=${encode(this.config.apiKey)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({returnSecureToken:true})});this.setSession(result);return result.localId;}
 // The host PlayPark app can later supply a custom token minted by its trusted server.
 async signInWithCustomToken(token){const result=await this.json(`https://identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken?key=${encode(this.config.apiKey)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,returnSecureToken:true})});this.setSession(result);return result.localId;}
 setSession(data){this.session={uid:data.localId,idToken:data.idToken,refreshToken:data.refreshToken,expiresAt:Date.now()+Math.max(60,Number(data.expiresIn)||3600)*1000};}
 async token(){if(this.tokenProvider)return this.tokenProvider();if(!this.session)throw Error('Not signed in');if(Date.now()<this.session.expiresAt-60000)return this.session.idToken;const result=await this.json(`https://securetoken.googleapis.com/v1/token?key=${encode(this.config.apiKey)}`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:this.session.refreshToken})});this.session={uid:result.user_id,idToken:result.id_token,refreshToken:result.refresh_token,expiresAt:Date.now()+Number(result.expires_in)*1000};return this.session.idToken;}
 async writeEvent(raw,id=crypto.randomUUID()){const event=cleanEvent({...raw,uid:this.session?.uid});const token=await this.token();const name=`projects/${this.config.projectId}/databases/(default)/documents/analyticsEvents/${encode(id)}`;return this.json(`${this.documents}:commit`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({writes:[{update:{name,fields:fieldsFor(event)},updateTransforms:[{fieldPath:'createdAt',setToServerValue:'REQUEST_TIME'}],currentDocument:{exists:false}}]})});}
 async listEvents(limit=3000){const token=await this.token(),events=[];let nextPageToken='';do{const url=new URL(`${this.documents}/analyticsEvents`);url.searchParams.set('pageSize',String(Math.min(1000,limit-events.length)));url.searchParams.set('orderBy','createdAt desc');if(nextPageToken)url.searchParams.set('pageToken',nextPageToken);const result=await this.json(url,{headers:{Authorization:`Bearer ${token}`}});events.push(...(result.documents||[]).map(firestoreEvent));nextPageToken=result.nextPageToken||'';}while(nextPageToken&&events.length<limit);return events;}
 signOut(){this.session=null;}
}
