// Reviewed learning content; generated by scripts/import-quiz.mjs.
export const quizSource={
  "sheet": "Quiz_DB",
  "snapshotDate": "2026-09-13",
  "sourceCount": 3008,
  "reviewedCount": 100
};
export const importedQuestions=[
  {
    "id": "db-100",
    "sourceId": 100,
    "sourceRow": 101,
    "category": "경기 지연 및 방해",
    "topic": "relief",
    "difficulty": 2,
    "question": "멈춘 공을 새가 물고 갔어요. 어떻게 할까요?",
    "answers": [
      "원래 있던 위치에 공을 놓아요",
      "새가 내려놓은 곳에서 계속 쳐요"
    ],
    "correct": 0,
    "explanation": "새 같은 국외자가 공을 움직였다면 벌타 없이 원래 위치로 되돌려요."
  },
  {
    "id": "db-124",
    "sourceId": 124,
    "sourceRow": 125,
    "category": "경기 지연 및 방해",
    "topic": "stroke",
    "difficulty": 2,
    "question": "친 공이 우연히 동반자를 맞고 멈췄어요. 공은 어디서 칠까요?",
    "answers": [
      "멈춘 자리에서 쳐요",
      "반드시 티로 돌아가요"
    ],
    "correct": 0,
    "explanation": "고의적인 방해가 아니라면 공은 멈춘 자리에서 이어 쳐요. 먼저 다친 사람이 없는지 확인해요."
  },
  {
    "id": "db-134",
    "sourceId": 134,
    "sourceRow": 135,
    "category": "경기 지연 및 방해",
    "topic": "manners",
    "difficulty": 3,
    "question": "대회 중 동반자에게 구체적인 스윙 방법을 조언해도 될까요?",
    "answers": [
      "허용되지 않는 조언은 2벌타예요",
      "어떤 기술 조언도 항상 허용돼요"
    ],
    "correct": 0,
    "explanation": "경기 중 기술적인 조언은 규칙의 제한을 받아요. 게임 속 플팍 안내는 학습을 위한 별도 도움 기능이에요."
  },
  {
    "id": "db-195",
    "sourceId": 195,
    "sourceRow": 196,
    "category": "그린 및 홀아웃",
    "topic": "green",
    "difficulty": 1,
    "question": "공이 깃대를 맞고 튕겨 나왔어요. 홀아웃일까요?",
    "answers": [
      "공을 컵에 넣을 때까지 계속 쳐요",
      "깃대에 닿았으니 홀아웃이에요"
    ],
    "correct": 0,
    "explanation": "깃대에 맞기만 해서는 홀아웃이 아니에요. 공을 홀컵에 넣어야 해요."
  },
  {
    "id": "db-209",
    "sourceId": 209,
    "sourceRow": 210,
    "category": "그린 및 홀아웃",
    "topic": "green",
    "difficulty": 1,
    "question": "공을 집어 들기 전, 볼 마커는 어디에 놓을까요?",
    "answers": [
      "홀컵을 기준으로 공 바로 뒤에 놓아요",
      "공과 상관없는 편한 곳에 놓아요"
    ],
    "correct": 0,
    "explanation": "공 뒤에 마크해 두면 공을 원래 자리에 정확히 되놓을 수 있어요."
  },
  {
    "id": "db-229",
    "sourceId": 229,
    "sourceRow": 230,
    "category": "그린 및 홀아웃",
    "topic": "score",
    "difficulty": 1,
    "question": "기준 타수와 같은 타수로 홀아웃하면 무엇일까요?",
    "answers": [
      "파예요",
      "버디예요"
    ],
    "correct": 0,
    "explanation": "기준 타수와 같으면 파, 기준보다 1타 적으면 버디예요."
  },
  {
    "id": "db-230",
    "sourceId": 230,
    "sourceRow": 231,
    "category": "그린 및 홀아웃",
    "topic": "green",
    "difficulty": 3,
    "question": "친 공이 멈춰 있던 다른 공을 맞힌 뒤 홀컵에 들어갔어요.",
    "answers": [
      "컵인은 인정하고 맞아 움직인 공은 원위치해요",
      "충돌한 두 공 모두 티로 돌아가요"
    ],
    "correct": 0,
    "explanation": "우연한 충돌이면 친 공의 컵인은 인정돼요. 원래 멈춰 있던 공은 있던 자리로 되돌려요."
  },
  {
    "id": "db-242",
    "sourceId": 242,
    "sourceRow": 243,
    "category": "그린 및 홀아웃",
    "topic": "green",
    "difficulty": 2,
    "question": "공이 홀컵 가장자리에 멈췄어요. 기다릴 수 있는 시간은?",
    "answers": [
      "10초예요",
      "제한 없이 기다릴 수 있어요"
    ],
    "correct": 0,
    "explanation": "컵 가장자리의 공은 10초 동안 기다릴 수 있어요. 끝없이 기다리며 경기를 지연하지 않아요."
  },
  {
    "id": "db-248",
    "sourceId": 248,
    "sourceRow": 249,
    "category": "그린 및 홀아웃",
    "topic": "manners",
    "difficulty": 1,
    "question": "동반자의 퍼팅 선을 가로질러 밟아도 될까요?",
    "answers": [
      "퍼팅 선을 피해 걸어요",
      "공만 안 밟으면 어디든 걸어요"
    ],
    "correct": 0,
    "explanation": "퍼팅 선은 공이 굴러갈 예상 경로예요. 잔디와 동반자의 플레이를 배려해 피해 걸어요."
  },
  {
    "id": "db-253",
    "sourceId": 253,
    "sourceRow": 254,
    "category": "그린 및 홀아웃",
    "topic": "tee",
    "difficulty": 2,
    "question": "그린 밖의 공이 그린 위 공보다 홀컵에 가까워요. 누가 먼저 칠까요?",
    "answers": [
      "그린 위라도 홀컵에서 더 먼 공부터 쳐요",
      "그린 밖의 공이 무조건 먼저예요"
    ],
    "correct": 0,
    "explanation": "티샷 이후 순서는 구역보다 홀컵까지의 거리를 기준으로 정해요."
  },
  {
    "id": "db-254",
    "sourceId": 254,
    "sourceRow": 255,
    "category": "그린 및 홀아웃",
    "topic": "manners",
    "difficulty": 1,
    "question": "내 공을 먼저 넣었어요. 다음 홀로 바로 가도 될까요?",
    "answers": [
      "동반자 모두 홀아웃할 때까지 기다려요",
      "내 점수만 말하고 먼저 가요"
    ],
    "correct": 0,
    "explanation": "모두 홀아웃한 뒤 점수를 확인하고 함께 이동해요."
  },
  {
    "id": "db-255",
    "sourceId": 255,
    "sourceRow": 256,
    "category": "그린 및 홀아웃",
    "topic": "green",
    "difficulty": 1,
    "question": "퍼팅한 공이 그린 밖으로 나갔지만 OB는 아니에요.",
    "answers": [
      "멈춘 자리에서 계속 쳐요",
      "그린 밖이면 무조건 2벌타예요"
    ],
    "correct": 0,
    "explanation": "그린 밖이라는 이유만으로 벌타를 받지 않아요. 공의 위치와 경계 안팎을 구분해요."
  },
  {
    "id": "db-256",
    "sourceId": 256,
    "sourceRow": 257,
    "category": "그린 및 홀아웃",
    "topic": "manners",
    "difficulty": 1,
    "question": "그린 위를 걸을 때 좋은 습관은?",
    "answers": [
      "발을 끌지 않고 걸어요",
      "발로 잔디를 긁으며 걸어요"
    ],
    "correct": 0,
    "explanation": "발을 끌면 잔디가 상하고 다음 사람의 퍼팅에도 영향을 줄 수 있어요."
  },
  {
    "id": "db-257",
    "sourceId": 257,
    "sourceRow": 258,
    "category": "그린 및 홀아웃",
    "topic": "manners",
    "difficulty": 1,
    "question": "동반자가 퍼팅을 준비할 때 어디서 기다릴까요?",
    "answers": [
      "시야를 방해하지 않는 안전한 곳이 좋아요",
      "공 바로 뒤에서 몸을 움직이며 지켜봐요"
    ],
    "correct": 0,
    "explanation": "집중을 방해하지 않게 조용히 멈추고 안전거리를 지켜요."
  },
  {
    "id": "db-258",
    "sourceId": 258,
    "sourceRow": 259,
    "category": "그린 및 홀아웃",
    "topic": "manners",
    "difficulty": 2,
    "question": "내 그림자가 동반자의 퍼팅 선을 덮고 있어요.",
    "answers": [
      "그림자가 방해하지 않도록 비켜요",
      "그림자는 관계없으니 그대로 있어요"
    ],
    "correct": 0,
    "explanation": "공과 퍼팅 선에 그림자를 드리우지 않는 것도 배려예요."
  },
  {
    "id": "db-266",
    "sourceId": 266,
    "sourceRow": 267,
    "category": "그린 및 홀아웃",
    "topic": "green",
    "difficulty": 1,
    "question": "공이 꽂혀 있는 깃대에 맞고 홀컵 안에 들어갔어요.",
    "answers": [
      "정상적인 컵인이에요",
      "깃대에 닿았으므로 다시 쳐요"
    ],
    "correct": 0,
    "explanation": "파크골프는 깃대를 꽂아 둔 채 플레이해요. 깃대에 닿아도 컵에 들어가면 인정돼요."
  },
  {
    "id": "db-280",
    "sourceId": 280,
    "sourceRow": 281,
    "category": "그린 및 홀아웃",
    "topic": "green",
    "difficulty": 1,
    "question": "내 공이 동반자의 샷에 방해되어 마크를 요청받았어요.",
    "answers": [
      "마크한 뒤 공을 집어 들어요",
      "무조건 거절하고 그대로 둬요"
    ],
    "correct": 0,
    "explanation": "방해되는 공은 요청에 따라 마크해요. 이후에는 정확히 원래 위치에 되놓아요."
  },
  {
    "id": "db-281",
    "sourceId": 281,
    "sourceRow": 282,
    "category": "그린 및 홀아웃",
    "topic": "basics",
    "difficulty": 1,
    "question": "볼 마커를 사용하는 가장 중요한 이유는?",
    "answers": [
      "공이 있던 위치를 기억하기 위해서예요",
      "홀컵 크기를 재기 위해서예요"
    ],
    "correct": 0,
    "explanation": "마커는 집어 든 공을 원래 위치에 되놓기 위한 표시예요."
  },
  {
    "id": "db-291",
    "sourceId": 291,
    "sourceRow": 292,
    "category": "그린 및 홀아웃",
    "topic": "score",
    "difficulty": 1,
    "question": "티샷 한 번으로 홀컵에 넣었어요. 무엇이라고 할까요?",
    "answers": [
      "홀인원이에요",
      "보기예요"
    ],
    "correct": 0,
    "explanation": "첫 샷 한 번으로 홀아웃하면 홀인원이에요. 벌타가 없다면 1타로 기록해요."
  },
  {
    "id": "db-346",
    "sourceId": 346,
    "sourceRow": 347,
    "category": "그린 및 홀아웃",
    "topic": "stroke",
    "difficulty": 2,
    "question": "공을 치기 전 바람에 공이 굴러갔어요. 어떻게 할까요?",
    "answers": [
      "공이 멈추기를 기다린 뒤 새 위치에서 쳐요",
      "움직이는 공을 쫓아가 바로 쳐요"
    ],
    "correct": 0,
    "explanation": "자연적인 바람으로 움직인 공은 멈춘 위치에서 이어 쳐요. 티 위에서 떨어진 경우는 티샷 전 규칙을 따로 적용해요."
  },
  {
    "id": "db-355",
    "sourceId": 355,
    "sourceRow": 356,
    "category": "그린 및 홀아웃",
    "topic": "manners",
    "difficulty": 1,
    "question": "동반자가 좋은 샷을 했을 때 어울리는 행동은?",
    "answers": [
      "플레이에 방해되지 않게 축하해요",
      "다음 샷까지 계속 큰 소리를 질러요"
    ],
    "correct": 0,
    "explanation": "좋은 플레이를 함께 기뻐하되 다음 사람의 집중도 배려해요."
  },
  {
    "id": "db-371",
    "sourceId": 371,
    "sourceRow": 372,
    "category": "그린 및 홀아웃",
    "topic": "stroke",
    "difficulty": 2,
    "question": "아직 굴러가는 공을 일부러 쳤어요.",
    "answers": [
      "친 타수에 2벌타도 더해요",
      "멈춘 공을 친 것과 똑같아요"
    ],
    "correct": 0,
    "explanation": "공이 완전히 멈춘 뒤 쳐야 해요. 움직이는 공을 치면 타격 1타와 2벌타를 계산해요."
  },
  {
    "id": "db-373",
    "sourceId": 373,
    "sourceRow": 374,
    "category": "그린 및 홀아웃",
    "topic": "manners",
    "difficulty": 1,
    "question": "동반자가 샷을 준비하는데 진행 방향 앞으로 걸어가도 될까요?",
    "answers": [
      "타격이 끝날 때까지 안전한 곳에서 기다려요",
      "빠르게 지나가면 괜찮아요"
    ],
    "correct": 0,
    "explanation": "공이 날아갈 수 있는 방향으로 먼저 나가지 않아요. 서로의 안전을 먼저 확인해요."
  },
  {
    "id": "db-438",
    "sourceId": 438,
    "sourceRow": 439,
    "category": "그린 및 홀아웃",
    "topic": "manners",
    "difficulty": 1,
    "question": "앞 조가 아직 공이 닿을 수 있는 거리에 있어요.",
    "answers": [
      "충분한 안전거리가 생길 때까지 기다려요",
      "빨리 진행하려고 먼저 쳐요"
    ],
    "correct": 0,
    "explanation": "공이 앞 조에 닿을 가능성이 있으면 타격을 기다려요."
  },
  {
    "id": "db-448",
    "sourceId": 448,
    "sourceRow": 449,
    "category": "그린 및 홀아웃",
    "topic": "manners",
    "difficulty": 1,
    "question": "그린 위에서 클럽에 체중을 싣고 기대어도 될까요?",
    "answers": [
      "잔디가 눌리지 않도록 조심해요",
      "세게 눌러도 그린에는 영향이 없어요"
    ],
    "correct": 0,
    "explanation": "클럽으로 잔디를 누르거나 파손하지 않도록 주의해요."
  },
  {
    "id": "db-451",
    "sourceId": 451,
    "sourceRow": 452,
    "category": "그린 및 홀아웃",
    "topic": "green",
    "difficulty": 2,
    "question": "퍼팅 선의 잔디를 발로 눌러 평평하게 만들었어요.",
    "answers": [
      "코스를 유리하게 고치면 2벌타예요",
      "퍼팅 전에는 자유롭게 고쳐도 돼요"
    ],
    "correct": 0,
    "explanation": "공이 잘 굴러가게 하려고 의도적으로 상태를 개선하면 안 돼요."
  },
  {
    "id": "db-453",
    "sourceId": 453,
    "sourceRow": 454,
    "category": "그린 및 홀아웃",
    "topic": "green",
    "difficulty": 1,
    "question": "홀컵 안의 공은 어떻게 꺼내는 게 좋을까요?",
    "answers": [
      "컵 가장자리를 상하지 않게 조심히 꺼내요",
      "클럽 헤드로 컵을 파서 꺼내요"
    ],
    "correct": 0,
    "explanation": "클럽으로 컵 가장자리를 손상시키지 않게 공을 꺼내요."
  },
  {
    "id": "db-545",
    "sourceId": 545,
    "sourceRow": 546,
    "category": "마크 및 볼 마커",
    "topic": "score",
    "difficulty": 3,
    "question": "실제보다 많은 타수가 적힌 스코어카드를 제출했어요.",
    "answers": [
      "제출한 높은 타수가 기록돼요",
      "자동으로 실제 타수로 낮춰 줘요"
    ],
    "correct": 0,
    "explanation": "높게 제출한 타수는 그대로 기록되므로 제출 전 반드시 확인해요."
  },
  {
    "id": "db-568",
    "sourceId": 568,
    "sourceRow": 569,
    "category": "마크 및 볼 마커",
    "topic": "green",
    "difficulty": 2,
    "question": "정상적으로 마크하는 과정에서 실수로 공을 건드렸어요.",
    "answers": [
      "벌타 없이 공을 원위치해요",
      "언제나 2벌타를 받아요"
    ],
    "correct": 0,
    "explanation": "정상적인 마크 과정의 우연한 접촉은 원위치해요. 마크와 관계없이 공을 움직이는 상황과 구별해요."
  },
  {
    "id": "db-575",
    "sourceId": 575,
    "sourceRow": 576,
    "category": "마크 및 볼 마커",
    "topic": "tee",
    "difficulty": 2,
    "question": "티잉 구역 밖에 공을 놓고 티샷했어요.",
    "answers": [
      "티샷 구역 위반으로 2벌타예요",
      "티만 사용하면 위치는 상관없어요"
    ],
    "correct": 0,
    "explanation": "첫 샷은 정해진 티잉 구역 안에서 해야 해요. 게임에서는 올바른 위치를 자동으로 준비해요."
  },
  {
    "id": "db-587",
    "sourceId": 587,
    "sourceRow": 588,
    "category": "마크 및 볼 마커",
    "topic": "score",
    "difficulty": 2,
    "question": "대회 스코어카드를 제출하기 전 꼭 확인할 것은?",
    "answers": [
      "점수와 필요한 서명이에요",
      "내 이름의 글씨 크기만 확인해요"
    ],
    "correct": 0,
    "explanation": "점수를 함께 확인하고 본인과 마커의 서명 등 제출 요건을 확인해요."
  },
  {
    "id": "db-775",
    "sourceId": 775,
    "sourceRow": 776,
    "category": "스윙 및 스트로크",
    "topic": "stroke",
    "difficulty": 2,
    "question": "샷 공간을 만들려고 자라는 나뭇가지를 일부러 꺾었어요.",
    "answers": [
      "상태를 개선한 위반으로 2벌타예요",
      "내 공 근처 가지는 마음대로 꺾어도 돼요"
    ],
    "correct": 0,
    "explanation": "유리한 스윙 공간을 만들려고 식물을 훼손하면 안 돼요. 정상적인 타격 중 상황과 구별해요."
  },
  {
    "id": "db-779",
    "sourceId": 779,
    "sourceRow": 780,
    "category": "스윙 및 스트로크",
    "topic": "score",
    "difficulty": 2,
    "question": "매치 플레이는 무엇으로 승부를 정할까요?",
    "answers": [
      "홀마다의 승패를 비교해요",
      "무조건 전체 타수 합계만 비교해요"
    ],
    "correct": 0,
    "explanation": "매치 플레이는 홀별 승패로 겨뤄요. 이 게임의 기본 경기는 18홀 합계 타수를 비교하는 스트로크 플레이예요."
  },
  {
    "id": "db-784",
    "sourceId": 784,
    "sourceRow": 785,
    "category": "스윙 및 스트로크",
    "topic": "basics",
    "difficulty": 3,
    "question": "정상적으로 친 공이 산산이 부서졌어요.",
    "answers": [
      "그 타격을 취소하고 새 공으로 원위치에서 쳐요",
      "조각 중 하나를 골라 계속 쳐요"
    ],
    "correct": 0,
    "explanation": "타격으로 공이 부서진 경우는 그 타격을 계산하지 않고 새 공으로 다시 쳐요."
  },
  {
    "id": "db-813",
    "sourceId": 813,
    "sourceRow": 814,
    "category": "스윙 및 스트로크",
    "topic": "relief",
    "difficulty": 1,
    "question": "공을 도저히 칠 수 없어 언플레이어블을 선언했어요.",
    "answers": [
      "2벌타를 더해 처치해요",
      "벌타 없이 원하는 곳으로 옮겨요"
    ],
    "correct": 0,
    "explanation": "언플레이어블은 2벌타를 더하고 규칙에 맞는 장소에 공을 놓는 처치예요."
  },
  {
    "id": "db-845",
    "sourceId": 845,
    "sourceRow": 846,
    "category": "스윙 및 스트로크",
    "topic": "relief",
    "difficulty": 1,
    "question": "공 주변에 떨어진 비닐봉지가 방해돼요.",
    "answers": [
      "공을 움직이지 않게 조심하며 치울 수 있어요",
      "쓰레기는 규칙상 절대 치울 수 없어요"
    ],
    "correct": 0,
    "explanation": "움직일 수 있는 인공 장애물은 치울 수 있어요. 공의 위치는 그대로 지켜요."
  },
  {
    "id": "db-888",
    "sourceId": 888,
    "sourceRow": 889,
    "category": "스윙 및 스트로크",
    "topic": "manners",
    "difficulty": 1,
    "question": "샷을 하며 잔디가 파였어요. 좋은 마무리는?",
    "answers": [
      "플레이 후 잔디를 정리해요",
      "뒤 조가 알아서 정리하게 둬요"
    ],
    "correct": 0,
    "explanation": "플레이로 손상된 잔디를 정리해 다음 사람도 코스를 즐길 수 있게 해요."
  },
  {
    "id": "db-913",
    "sourceId": 913,
    "sourceRow": 914,
    "category": "스윙 및 스트로크",
    "topic": "basics",
    "difficulty": 1,
    "question": "샷 전 일정한 준비 동작인 루틴은 무엇을 도울까요?",
    "answers": [
      "차분하고 일관된 준비를 도와요",
      "매번 다른 방법으로 급하게 치게 해요"
    ],
    "correct": 0,
    "explanation": "방향과 안전을 확인하는 짧은 루틴을 정하면 차분하게 준비할 수 있어요."
  },
  {
    "id": "db-917",
    "sourceId": 917,
    "sourceRow": 918,
    "category": "스윙 및 스트로크",
    "topic": "basics",
    "difficulty": 1,
    "question": "실수한 샷 다음에 도움이 되는 마음가짐은?",
    "answers": [
      "마음을 가다듬고 다음 샷에 집중해요",
      "지난 실수만 계속 떠올리며 급히 쳐요"
    ],
    "correct": 0,
    "explanation": "한 번의 실수보다 지금 할 수 있는 다음 샷에 집중해 봐요."
  },
  {
    "id": "db-964",
    "sourceId": 964,
    "sourceRow": 965,
    "category": "스윙 및 스트로크",
    "topic": "manners",
    "difficulty": 1,
    "question": "동반자가 스윙하는 동안 휴대전화가 울렸어요.",
    "answers": [
      "소리를 줄이고 플레이를 방해하지 않아요",
      "바로 옆에서 큰 소리로 통화해요"
    ],
    "correct": 0,
    "explanation": "라운드 전 무음이나 진동으로 설정하고 통화는 방해되지 않는 곳에서 해요."
  },
  {
    "id": "db-1023",
    "sourceId": 1023,
    "sourceRow": 1024,
    "category": "스윙 및 스트로크",
    "topic": "basics",
    "difficulty": 3,
    "question": "대회에서 클럽 타구면에 임의로 물질을 덧붙여도 될까요?",
    "answers": [
      "용구를 임의로 개조하면 안 돼요",
      "공이 잘 맞기만 하면 어떤 개조도 돼요"
    ],
    "correct": 0,
    "explanation": "성능을 바꾸기 위해 규정에 맞지 않게 개조한 용구는 사용할 수 없어요."
  },
  {
    "id": "db-1024",
    "sourceId": 1024,
    "sourceRow": 1025,
    "category": "스윙 및 스트로크",
    "topic": "basics",
    "difficulty": 2,
    "question": "경기 중 공에 손상이 생겨 교체하려고 해요.",
    "answers": [
      "동반자나 심판에게 확인받고 교체해요",
      "알리지 않고 좋은 공으로 바꿔요"
    ],
    "correct": 0,
    "explanation": "사용 불가능한 손상이 있는지 확인받은 뒤 규칙에 맞게 교체해요."
  },
  {
    "id": "db-1041",
    "sourceId": 1041,
    "sourceRow": 1042,
    "category": "스윙 및 스트로크",
    "topic": "basics",
    "difficulty": 2,
    "question": "퍼팅이 잘 안 돼서 동반자의 클럽을 빌려 쳐도 될까요?",
    "answers": [
      "경기 중 임의로 클럽을 바꾸지 않아요",
      "매 샷 원하는 클럽을 빌려 써요"
    ],
    "correct": 0,
    "explanation": "파크골프는 한 개의 클럽으로 플레이해요. 단순히 샷이 안 된다는 이유로 바꾸지 않아요."
  },
  {
    "id": "db-1072",
    "sourceId": 1072,
    "sourceRow": 1073,
    "category": "스윙 및 스트로크",
    "topic": "basics",
    "difficulty": 2,
    "question": "정상적인 플레이 중 클럽이 부러졌어요.",
    "answers": [
      "동반자나 심판에게 알리고 교체할 수 있어요",
      "어떤 파손도 교체할 수 없어요"
    ],
    "correct": 0,
    "explanation": "정상적인 플레이로 손상된 클럽은 규칙에 따라 교체할 수 있어요."
  },
  {
    "id": "db-1074",
    "sourceId": 1074,
    "sourceRow": 1075,
    "category": "스윙 및 스트로크",
    "topic": "stroke",
    "difficulty": 1,
    "question": "공을 치려는 샷이 공에 닿았지만 아주 조금만 움직였어요.",
    "answers": [
      "1타로 계산해요",
      "멀리 가지 않았으니 0타예요"
    ],
    "correct": 0,
    "explanation": "공을 치려는 타격이 공에 닿았다면 이동 거리가 짧아도 1타예요."
  },
  {
    "id": "db-1082",
    "sourceId": 1082,
    "sourceRow": 1083,
    "category": "스윙 및 스트로크",
    "topic": "green",
    "difficulty": 1,
    "question": "다른 공이 내 샷에 방해될 것 같아요.",
    "answers": [
      "상대에게 마크를 요청해요",
      "상대 공을 클럽으로 밀어 치워요"
    ],
    "correct": 0,
    "explanation": "다른 공은 임의로 움직이지 않아요. 소유자에게 마크를 요청해요."
  },
  {
    "id": "db-1111",
    "sourceId": 1111,
    "sourceRow": 1112,
    "category": "스코어 및 타수",
    "topic": "stroke",
    "difficulty": 3,
    "question": "한 번의 샷에서 클럽이 공에 두 번 닿았어요.",
    "answers": [
      "타격 1타에 2벌타를 더해요",
      "두 번 닿아도 벌타는 없어요"
    ],
    "correct": 0,
    "explanation": "파크골프의 2회 타구 규정을 적용해 총 3타를 계산해요. 일반 골프 규칙과 혼동하지 않아요."
  },
  {
    "id": "db-1112",
    "sourceId": 1112,
    "sourceRow": 1113,
    "category": "스코어 및 타수",
    "topic": "score",
    "difficulty": 1,
    "question": "스트로크 플레이의 승자는 누구일까요?",
    "answers": [
      "정해진 홀의 총 타수가 가장 적은 선수예요",
      "가장 멀리 친 선수예요"
    ],
    "correct": 0,
    "explanation": "샷과 벌타를 모두 합산한 총 타수로 비교해요. 이 게임도 같은 방식이에요."
  },
  {
    "id": "db-1118",
    "sourceId": 1118,
    "sourceRow": 1119,
    "category": "스코어 및 타수",
    "topic": "score",
    "difficulty": 3,
    "question": "실제보다 적은 타수를 적어 제출하면 어떻게 될까요?",
    "answers": [
      "실격 사유가 돼요",
      "잘못 적은 만큼만 나중에 더해요"
    ],
    "correct": 0,
    "explanation": "실제보다 낮은 타수를 제출하면 실격이 될 수 있으므로 타수와 벌타를 정확히 확인해요."
  },
  {
    "id": "db-1167",
    "sourceId": 1167,
    "sourceRow": 1168,
    "category": "스코어 및 타수",
    "topic": "score",
    "difficulty": 1,
    "question": "파 4홀을 2타 만에 마쳤어요. 무엇일까요?",
    "answers": [
      "이글이에요",
      "보기예요"
    ],
    "correct": 0,
    "explanation": "기준보다 2타 적으면 이글이에요. 4에서 2를 빼면 2타 적은 기록이에요."
  },
  {
    "id": "db-1170",
    "sourceId": 1170,
    "sourceRow": 1171,
    "category": "스코어 및 타수",
    "topic": "score",
    "difficulty": 1,
    "question": "홀아웃 후 점수를 어디서 정리하는 게 좋을까요?",
    "answers": [
      "그린을 비운 뒤 다음 티 쪽에서 확인해요",
      "그린을 막고 오래 머물며 적어요"
    ],
    "correct": 0,
    "explanation": "모두의 타수를 확인하되 뒤 조가 플레이할 수 있도록 그린을 비워 주세요."
  },
  {
    "id": "db-1178",
    "sourceId": 1178,
    "sourceRow": 1179,
    "category": "스코어 및 타수",
    "topic": "score",
    "difficulty": 2,
    "question": "스코어카드 제출 직전에 할 일은?",
    "answers": [
      "동반자와 타수·벌타를 다시 확인해요",
      "대충 적고 바로 제출해요"
    ],
    "correct": 0,
    "explanation": "한 홀씩 타수와 벌타를 확인하면 누락과 오기를 줄일 수 있어요."
  },
  {
    "id": "db-1214",
    "sourceId": 1214,
    "sourceRow": 1215,
    "category": "스코어 및 타수",
    "topic": "score",
    "difficulty": 2,
    "question": "유리한 순위를 얻으려고 점수를 고쳐 적었어요.",
    "answers": [
      "정직한 기록을 어긴 실격 사유예요",
      "들키지 않으면 괜찮아요"
    ],
    "correct": 0,
    "explanation": "스코어는 실제 타격과 벌타를 정직하게 기록해야 해요."
  },
  {
    "id": "db-1231",
    "sourceId": 1231,
    "sourceRow": 1232,
    "category": "스코어 및 타수",
    "topic": "score",
    "difficulty": 1,
    "question": "파 3홀 4개, 파 4홀 4개, 파 5홀 1개의 기준 타수 합은?",
    "answers": [
      "33타예요",
      "36타예요"
    ],
    "correct": 0,
    "explanation": "3×4 + 4×4 + 5×1 = 33이에요. 이 게임의 각 9홀 코스도 PAR 33이에요."
  },
  {
    "id": "db-1238",
    "sourceId": 1238,
    "sourceRow": 1239,
    "category": "스코어 및 타수",
    "topic": "stroke",
    "difficulty": 2,
    "question": "공에 닿지 않는 헛스윙 뒤, 다시 쳐서 공을 보냈어요.",
    "answers": [
      "벌타가 없다면 1타예요",
      "헛스윙까지 합쳐 2타예요"
    ],
    "correct": 0,
    "explanation": "파크골프에서 공에 닿지 않고 공도 움직이지 않은 헛스윙은 타수에 넣지 않아요."
  },
  {
    "id": "db-1387",
    "sourceId": 1387,
    "sourceRow": 1388,
    "category": "일반 지식 및 기타",
    "topic": "manners",
    "difficulty": 1,
    "question": "앞 조와 간격이 너무 벌어지고 있어요. 어떻게 할까요?",
    "answers": [
      "안전을 지키며 불필요한 지연을 줄여요",
      "뒤 조가 기다리든 말든 계속 쉬어요"
    ],
    "correct": 0,
    "explanation": "충분한 안전거리는 유지하고 준비와 이동을 원활하게 해요."
  },
  {
    "id": "db-1708",
    "sourceId": 1708,
    "sourceRow": 1709,
    "category": "일반 지식 및 기타",
    "topic": "basics",
    "difficulty": 1,
    "question": "파크골프의 이름은 어떤 말에서 왔을까요?",
    "answers": [
      "공원과 골프를 합친 말이에요",
      "주차장과 볼링을 합친 말이에요"
    ],
    "correct": 0,
    "explanation": "파크는 공원을 뜻해요. 공원에서 즐기는 골프라는 뜻이 담겨 있어요."
  },
  {
    "id": "db-2579",
    "sourceId": 2579,
    "sourceRow": 2580,
    "category": "티샷 및 티잉 그라운드",
    "topic": "tee",
    "difficulty": 2,
    "question": "티 위에서 공을 치려다 살짝 건드려 공이 떨어졌어요.",
    "answers": [
      "타격으로 공에 닿았다면 1타예요",
      "짧게 떨어졌으니 항상 다시 티업해요"
    ],
    "correct": 0,
    "explanation": "공을 치려는 타격과 바람에 저절로 떨어진 상황은 달라요. 실제 타격은 1타로 세어요."
  },
  {
    "id": "db-1727",
    "sourceId": 1727,
    "sourceRow": 1728,
    "category": "장비 및 용구",
    "topic": "stroke",
    "difficulty": 2,
    "question": "목표를 겨누기 위해 지면에 별도 표시를 해도 될까요?",
    "answers": [
      "방향을 위한 표시를 만들면 안 돼요",
      "샷 전에 원하는 표시를 그려도 돼요"
    ],
    "correct": 0,
    "explanation": "겨냥을 돕는 표시로 플레이 조건을 바꾸지 않아요."
  },
  {
    "id": "db-1784",
    "sourceId": 1784,
    "sourceRow": 1785,
    "category": "장비 및 용구",
    "topic": "stroke",
    "difficulty": 2,
    "question": "긴 풀 속 공 주변을 발로 밟아 치기 편하게 만들었어요.",
    "answers": [
      "상태를 유리하게 개선하면 2벌타예요",
      "내 공 주변은 마음대로 밟아도 돼요"
    ],
    "correct": 0,
    "explanation": "공 주변 상태를 의도적으로 바꾸지 않고 놓인 상태에서 쳐요."
  },
  {
    "id": "db-1800",
    "sourceId": 1800,
    "sourceRow": 1801,
    "category": "장비 및 용구",
    "topic": "basics",
    "difficulty": 1,
    "question": "티샷부터 퍼팅까지 기본적으로 몇 개의 클럽을 사용할까요?",
    "answers": [
      "한 개예요",
      "거리마다 여러 개를 골라요"
    ],
    "correct": 0,
    "explanation": "파크골프는 하나의 클럽으로 힘과 방향을 조절하며 플레이해요."
  },
  {
    "id": "db-1805",
    "sourceId": 1805,
    "sourceRow": 1806,
    "category": "장비 및 용구",
    "topic": "basics",
    "difficulty": 1,
    "question": "비에 젖은 클럽을 사용한 뒤 보관할 때는?",
    "answers": [
      "물기를 닦고 말린 뒤 보관해요",
      "젖은 채로 밀폐해 오래 둬요"
    ],
    "correct": 0,
    "explanation": "사용 후 물기와 오염을 정리하면 용구를 관리하는 데 도움이 돼요."
  },
  {
    "id": "db-1807",
    "sourceId": 1807,
    "sourceRow": 1808,
    "category": "장비 및 용구",
    "topic": "basics",
    "difficulty": 3,
    "question": "공의 성능을 바꾸려고 임의로 가공해도 될까요?",
    "answers": [
      "규정에 맞는 공을 그대로 사용해요",
      "잘 굴러가면 어떤 가공도 허용돼요"
    ],
    "correct": 0,
    "explanation": "규정에 맞는 용구를 사용하고 성능을 바꾸는 임의 개조를 하지 않아요."
  },
  {
    "id": "db-1830",
    "sourceId": 1830,
    "sourceRow": 1831,
    "category": "장비 및 용구",
    "topic": "basics",
    "difficulty": 1,
    "question": "클럽 헤드의 바닥이 넓고 평평한 이유는 무엇일까요?",
    "answers": [
      "잔디 위에서 부드럽게 미끄러지도록 도와요",
      "잔디를 깊이 파내기 위해서예요"
    ],
    "correct": 0,
    "explanation": "넓고 평평한 바닥은 잔디를 보호하며 스윙하는 데 도움을 줘요."
  },
  {
    "id": "db-1838",
    "sourceId": 1838,
    "sourceRow": 1839,
    "category": "장비 및 용구",
    "topic": "basics",
    "difficulty": 3,
    "question": "화가 나서 클럽을 부러뜨렸어요. 정상 파손처럼 교체할 수 있을까요?",
    "answers": [
      "고의 파손은 정상 플레이 중 파손과 달라요",
      "이유와 관계없이 자유롭게 교체해요"
    ],
    "correct": 0,
    "explanation": "정상적인 플레이 중 손상된 경우의 교체 규정을 고의 파손에 적용하지 않아요."
  },
  {
    "id": "db-1891",
    "sourceId": 1891,
    "sourceRow": 1892,
    "category": "장비 및 용구",
    "topic": "basics",
    "difficulty": 1,
    "question": "클럽하우스는 보통 어떤 곳일까요?",
    "answers": [
      "이용 안내와 휴식 등을 돕는 시설이에요",
      "반드시 공을 치는 타격 구역이에요"
    ],
    "correct": 0,
    "explanation": "클럽하우스는 접수와 안내, 휴식 등 구장 이용을 돕는 시설이에요."
  },
  {
    "id": "db-1929",
    "sourceId": 1929,
    "sourceRow": 1930,
    "category": "장해물 및 구제",
    "topic": "relief",
    "difficulty": 2,
    "question": "언플레이어블 처치로 공을 놓을 때 기본 조건은?",
    "answers": [
      "홀에 가깝지 않은 2클럽 이내예요",
      "홀컵 쪽으로 원하는 만큼 옮겨요"
    ],
    "correct": 0,
    "explanation": "기준 위치에서 홀컵에 가까워지지 않는 2클럽 이내에 놓아요. 놓을 곳이 없을 때는 정해진 처치를 따라요."
  },
  {
    "id": "db-1939",
    "sourceId": 1939,
    "sourceRow": 1940,
    "category": "장해물 및 구제",
    "topic": "stroke",
    "difficulty": 2,
    "question": "공을 클럽으로 밀거나 끌어서 보냈어요.",
    "answers": [
      "타격 방식 위반으로 2벌타를 더해요",
      "굴러가기만 하면 올바른 타격이에요"
    ],
    "correct": 0,
    "explanation": "공은 정상적인 타격으로 보내야 해요. 밀거나 끄는 동작은 허용되지 않아요."
  },
  {
    "id": "db-1946",
    "sourceId": 1946,
    "sourceRow": 1947,
    "category": "장해물 및 구제",
    "topic": "relief",
    "difficulty": 1,
    "question": "공 옆에 떨어져 있는 작은 나뭇가지가 방해돼요.",
    "answers": [
      "공을 움직이지 않게 조심하며 치울 수 있어요",
      "땅에 떨어진 가지도 절대 못 치워요"
    ],
    "correct": 0,
    "explanation": "떨어져 있는 자연물과 자라고 있는 식물은 달라요. 공의 위치는 그대로 유지해요."
  },
  {
    "id": "db-2001",
    "sourceId": 2001,
    "sourceRow": 2002,
    "category": "장해물 및 구제",
    "topic": "relief",
    "difficulty": 2,
    "question": "공이 경계망에 맞고 되돌아와 경계 안에 멈췄어요.",
    "answers": [
      "경계 안이면 그대로 플레이해요",
      "경계망에 닿기만 해도 무조건 OB예요"
    ],
    "correct": 0,
    "explanation": "경계망 접촉 자체가 OB는 아니에요. 최종 정지 위치와 OB 경계를 확인해요."
  },
  {
    "id": "db-2036",
    "sourceId": 2036,
    "sourceRow": 2037,
    "category": "장해물 및 구제",
    "topic": "relief",
    "difficulty": 1,
    "question": "공 옆에 떨어진 솔방울은 어떻게 할까요?",
    "answers": [
      "공을 움직이지 않도록 주의하며 치워요",
      "발로 공과 함께 밀어 치워요"
    ],
    "correct": 0,
    "explanation": "떨어진 자연물은 치울 수 있지만 공은 임의로 움직이지 않아요."
  },
  {
    "id": "db-2041",
    "sourceId": 2041,
    "sourceRow": 2042,
    "category": "장해물 및 구제",
    "topic": "relief",
    "difficulty": 2,
    "question": "자라는 나무가 샷을 가로막고 있어요.",
    "answers": [
      "그대로 치거나 필요한 규칙상 처치를 해요",
      "나무를 옮기거나 꺾어 길을 만들어요"
    ],
    "correct": 0,
    "explanation": "고정된 자연물을 마음대로 고칠 수 없어요. 칠 수 없으면 언플레이어블 등의 처치를 판단해요."
  },
  {
    "id": "db-2046",
    "sourceId": 2046,
    "sourceRow": 2047,
    "category": "장해물 및 구제",
    "topic": "relief",
    "difficulty": 2,
    "question": "고정된 코스 표지판이 방해돼요.",
    "answers": [
      "표지판을 뽑지 말고 규칙에 따른 처치를 확인해요",
      "유리한 샷을 위해 표지판부터 뽑아요"
    ],
    "correct": 0,
    "explanation": "고정 시설을 마음대로 옮겨서는 안 돼요. 구제 가능 여부와 대회 규칙을 확인해요."
  },
  {
    "id": "db-2050",
    "sourceId": 2050,
    "sourceRow": 2051,
    "category": "장해물 및 구제",
    "topic": "relief",
    "difficulty": 1,
    "question": "공 근처에 깎여 떨어진 잔디가 있어요.",
    "answers": [
      "공을 움직이지 않도록 조심해서 치워요",
      "공을 좋은 잔디 위로 함께 옮겨요"
    ],
    "correct": 0,
    "explanation": "떨어진 잔디를 치우는 것과 공의 위치를 임의로 바꾸는 것은 달라요."
  },
  {
    "id": "db-2063",
    "sourceId": 2063,
    "sourceRow": 2064,
    "category": "장해물 및 구제",
    "topic": "stroke",
    "difficulty": 2,
    "question": "벙커의 모래를 일부러 다져 샷하기 편하게 만들었어요.",
    "answers": [
      "상태를 개선한 위반으로 2벌타예요",
      "벙커에서는 모든 바닥 정리가 허용돼요"
    ],
    "correct": 0,
    "explanation": "정상적인 스탠스를 위한 동작과 유리하게 바닥을 다지는 행위를 구분해요."
  },
  {
    "id": "db-2483",
    "sourceId": 2483,
    "sourceRow": 2484,
    "category": "티샷 및 티잉 그라운드",
    "topic": "tee",
    "difficulty": 1,
    "question": "첫 타격 전에 바람 때문에 티 위의 공이 떨어졌어요.",
    "answers": [
      "벌타 없이 다시 티 위에 놓아요",
      "바람에 떨어져도 무조건 1타예요"
    ],
    "correct": 0,
    "explanation": "아직 타격하지 않았다면 티 위에 다시 놓고 준비해요."
  },
  {
    "id": "db-2484",
    "sourceId": 2484,
    "sourceRow": 2485,
    "category": "티샷 및 티잉 그라운드",
    "topic": "tee",
    "difficulty": 2,
    "question": "티샷할 때 발이 티잉 구역 밖으로 나가도 될까요?",
    "answers": [
      "양발을 구역 안에 두고 쳐요",
      "공만 안에 있으면 발은 자유로워요"
    ],
    "correct": 0,
    "explanation": "티샷은 공과 양발 모두 정해진 티잉 구역 안에서 해야 해요."
  },
  {
    "id": "db-2509",
    "sourceId": 2509,
    "sourceRow": 2510,
    "category": "티샷 및 티잉 그라운드",
    "topic": "manners",
    "difficulty": 1,
    "question": "스윙하는 사람에게 너무 가까이 서 있으면 왜 위험할까요?",
    "answers": [
      "클럽이나 공에 맞을 수 있어요",
      "가까울수록 항상 안전해요"
    ],
    "correct": 0,
    "explanation": "타격 전 주변을 살피고, 기다리는 사람도 스윙 범위 밖에서 안전거리를 지켜요."
  },
  {
    "id": "db-2511",
    "sourceId": 2511,
    "sourceRow": 2512,
    "category": "티샷 및 티잉 그라운드",
    "topic": "manners",
    "difficulty": 1,
    "question": "공이 사람 쪽으로 날아가고 있어요. 어떻게 할까요?",
    "answers": [
      "즉시 큰 소리로 위험을 알려요",
      "아무 말 없이 공만 지켜봐요"
    ],
    "correct": 0,
    "explanation": "볼 또는 포어처럼 분명한 소리로 주변에 위험을 알려요."
  },
  {
    "id": "db-2515",
    "sourceId": 2515,
    "sourceRow": 2516,
    "category": "티샷 및 티잉 그라운드",
    "topic": "manners",
    "difficulty": 1,
    "question": "친 공이 사람을 맞혔어요. 가장 먼저 할 일은?",
    "answers": [
      "플레이를 멈추고 상태를 확인해요",
      "벌타부터 따지며 다음 샷을 쳐요"
    ],
    "correct": 0,
    "explanation": "사람의 안전이 먼저예요. 상태를 확인하고 필요한 도움을 요청해요."
  },
  {
    "id": "db-2540",
    "sourceId": 2540,
    "sourceRow": 2541,
    "category": "티샷 및 티잉 그라운드",
    "topic": "tee",
    "difficulty": 1,
    "question": "헛스윙했지만 공에 닿지 않았고 공도 움직이지 않았어요.",
    "answers": [
      "타수에 넣지 않아요",
      "반드시 1타를 더해요"
    ],
    "correct": 0,
    "explanation": "파크골프에서는 공에 닿지 않고 움직이지 않은 헛스윙은 0타예요."
  },
  {
    "id": "db-2545",
    "sourceId": 2545,
    "sourceRow": 2546,
    "category": "티샷 및 티잉 그라운드",
    "topic": "tee",
    "difficulty": 1,
    "question": "첫 홀의 티샷 순서는 보통 어떻게 정할까요?",
    "answers": [
      "제비뽑기 등으로 정해요",
      "나이가 가장 많은 사람이 항상 먼저예요"
    ],
    "correct": 0,
    "explanation": "첫 홀은 추첨 등으로 순서를 정해요. 이 게임도 시작 순서를 뽑아요."
  },
  {
    "id": "db-2567",
    "sourceId": 2567,
    "sourceRow": 2568,
    "category": "티샷 및 티잉 그라운드",
    "topic": "basics",
    "difficulty": 1,
    "question": "일반 골프의 드라이버로 파크골프 대회를 쳐도 될까요?",
    "answers": [
      "파크골프 규격에 맞는 클럽을 사용해요",
      "공이 맞기만 하면 어떤 클럽도 돼요"
    ],
    "correct": 0,
    "explanation": "참가하는 경기의 용구 규격을 지켜야 해요."
  },
  {
    "id": "db-2568",
    "sourceId": 2568,
    "sourceRow": 2569,
    "category": "티샷 및 티잉 그라운드",
    "topic": "tee",
    "difficulty": 1,
    "question": "티샷을 마친 뒤에는 어떻게 할까요?",
    "answers": [
      "다음 선수가 준비할 수 있게 비켜요",
      "티잉 구역 가운데 계속 서 있어요"
    ],
    "correct": 0,
    "explanation": "티샷을 마치면 안전하게 비켜 다음 사람의 준비를 도와요."
  },
  {
    "id": "db-2573",
    "sourceId": 2573,
    "sourceRow": 2574,
    "category": "티샷 및 티잉 그라운드",
    "topic": "tee",
    "difficulty": 2,
    "question": "첫 샷 때 티 없이 공을 바닥에 놓고 쳤어요.",
    "answers": [
      "티업 규정 위반으로 2벌타예요",
      "첫 샷도 티는 필요 없어요"
    ],
    "correct": 0,
    "explanation": "파크골프의 첫 샷은 티 위에 공을 올려놓고 해야 해요."
  },
  {
    "id": "db-2574",
    "sourceId": 2574,
    "sourceRow": 2575,
    "category": "티샷 및 티잉 그라운드",
    "topic": "tee",
    "difficulty": 1,
    "question": "다음 홀의 첫 티샷은 누가 할까요?",
    "answers": [
      "직전 홀 타수가 가장 적은 선수예요",
      "직전 홀 타수가 가장 많은 선수예요"
    ],
    "correct": 0,
    "explanation": "직전 홀의 최저 타수 선수가 먼저예요. 동점이면 그전의 순서를 유지해요."
  },
  {
    "id": "db-2582",
    "sourceId": 2582,
    "sourceRow": 2583,
    "category": "티샷 및 티잉 그라운드",
    "topic": "tee",
    "difficulty": 3,
    "question": "티샷이 티잉 구역 안에 멈췄어요. 다음 타격은?",
    "answers": [
      "공이 멈춘 자리에서 이어 쳐요",
      "무조건 새 티샷으로 처음부터 시작해요"
    ],
    "correct": 0,
    "explanation": "첫 타격을 계산하고 멈춘 자리에서 계속해요. 다른 사람의 안전과 진행 순서도 확인해요."
  },
  {
    "id": "db-2591",
    "sourceId": 2591,
    "sourceRow": 2592,
    "category": "티샷 및 티잉 그라운드",
    "topic": "tee",
    "difficulty": 1,
    "question": "티샷 전 연습 스윙을 하려면 먼저 무엇을 확인할까요?",
    "answers": [
      "클럽이 닿을 범위에 사람이 없는지 확인해요",
      "공을 얼마나 멀리 보낼지만 생각해요"
    ],
    "correct": 0,
    "explanation": "연습 스윙도 클럽이 사람에게 닿을 수 있어요. 안전 확인이 먼저예요."
  },
  {
    "id": "db-2604",
    "sourceId": 2604,
    "sourceRow": 2605,
    "category": "티샷 및 티잉 그라운드",
    "topic": "tee",
    "difficulty": 3,
    "question": "공에 닿지 않는 헛스윙 뒤 바람에 공이 티에서 떨어졌어요.",
    "answers": [
      "타격 전이라면 벌타 없이 다시 티업해요",
      "헛스윙과 바람을 합쳐 2타예요"
    ],
    "correct": 0,
    "explanation": "공에 닿지 않은 헛스윙은 타수가 아니에요. 타격 전 바람으로 떨어진 공은 다시 올려놓아요."
  },
  {
    "id": "db-2618",
    "sourceId": 2618,
    "sourceRow": 2619,
    "category": "퍼팅 및 깃대",
    "topic": "green",
    "difficulty": 2,
    "question": "두 공이 서로의 퍼팅에 방해되고 있어요.",
    "answers": [
      "필요한 공을 마크하고 순서대로 쳐요",
      "한 사람이 두 공을 한꺼번에 쳐요"
    ],
    "correct": 0,
    "explanation": "공을 임의로 건드리지 말고 마크한 뒤 홀컵에서 먼 공부터 플레이해요."
  },
  {
    "id": "db-2674",
    "sourceId": 2674,
    "sourceRow": 2675,
    "category": "퍼팅 및 깃대",
    "topic": "stroke",
    "difficulty": 2,
    "question": "방향을 맞추려고 클럽을 지면에 놓아 표시해도 될까요?",
    "answers": [
      "겨냥 표시로 사용하지 않아요",
      "원하는 곳에 계속 놓아도 돼요"
    ],
    "correct": 0,
    "explanation": "방향을 위한 표시를 만들어 플레이 조건을 바꾸지 않아요."
  },
  {
    "id": "db-2923",
    "sourceId": 2923,
    "sourceRow": 2924,
    "category": "OB",
    "topic": "relief",
    "difficulty": 1,
    "question": "파크골프에서 OB가 나면 몇 벌타를 더할까요?",
    "answers": [
      "2벌타예요",
      "1벌타예요"
    ],
    "correct": 0,
    "explanation": "친 타수에 OB 2벌타를 더하고 정해진 위치에서 이어 쳐요."
  },
  {
    "id": "db-2929",
    "sourceId": 2929,
    "sourceRow": 2930,
    "category": "OB",
    "topic": "relief",
    "difficulty": 2,
    "question": "OB 처치 때 홀컵에 더 가까운 곳에 공을 놓아도 될까요?",
    "answers": [
      "홀컵에 가까워지지 않는 곳에 놓아요",
      "가까운 곳일수록 우선해서 놓아요"
    ],
    "correct": 0,
    "explanation": "거리가 유리해지지 않도록 경계 지점을 기준으로 올바르게 처치해요."
  },
  {
    "id": "db-2937",
    "sourceId": 2937,
    "sourceRow": 2938,
    "category": "OB",
    "topic": "relief",
    "difficulty": 2,
    "question": "공이 OB인지 동반자끼리 판단이 달라요.",
    "answers": [
      "위치와 경계를 함께 확인하고 필요하면 심판에게 물어요",
      "내게 유리한 판정으로 혼자 진행해요"
    ],
    "correct": 0,
    "explanation": "애매한 판정은 공을 임의로 옮기기 전에 동반자나 심판과 확인해요."
  },
  {
    "id": "db-2959",
    "sourceId": 2959,
    "sourceRow": 2960,
    "category": "OB",
    "topic": "relief",
    "difficulty": 3,
    "question": "내 공이 멈춘 다른 공에 부딪힌 뒤 내 공이 OB로 나갔어요.",
    "answers": [
      "내 공은 OB 처치하고 맞아 움직인 공은 원위치해요",
      "다른 공에 맞았으니 내 OB는 취소돼요"
    ],
    "correct": 0,
    "explanation": "내 공이 최종적으로 OB에 멈췄으면 2벌타를 더해 처치해요. 맞아 움직인 다른 공은 원래 위치로 돌려놓아요."
  },
  {
    "id": "db-2962",
    "sourceId": 2962,
    "sourceRow": 2963,
    "category": "OB",
    "topic": "score",
    "difficulty": 2,
    "question": "티샷이 OB가 되어 2벌타를 받았어요. 다음은 몇 번째 샷일까요?",
    "answers": [
      "4번째 샷이에요",
      "2번째 샷이에요"
    ],
    "correct": 0,
    "explanation": "티샷 1타와 벌타 2타로 현재 3타예요. 다음 타격이 4번째 샷이에요."
  },
  {
    "id": "db-2964",
    "sourceId": 2964,
    "sourceRow": 2965,
    "category": "OB",
    "topic": "relief",
    "difficulty": 2,
    "question": "OB 처치 후 다시 친 공이 또 OB예요.",
    "answers": [
      "이번 OB에도 2벌타를 더해요",
      "한 홀에서는 OB 벌타를 한 번만 더해요"
    ],
    "correct": 0,
    "explanation": "새로운 타격에서 다시 OB가 나면 그 타격과 추가 2벌타를 계산해요."
  },
  {
    "id": "db-2985",
    "sourceId": 2985,
    "sourceRow": 2986,
    "category": "OB",
    "topic": "score",
    "difficulty": 3,
    "question": "티샷 OB 후 2벌타를 받고, 다음 한 번의 샷으로 컵인했어요.",
    "answers": [
      "이 홀은 4타예요",
      "컵인 샷만 계산해 1타예요"
    ],
    "correct": 0,
    "explanation": "첫 샷 1타 + OB 2벌타 + 컵인 샷 1타 = 4타예요."
  },
  {
    "id": "db-3002",
    "sourceId": 3002,
    "sourceRow": 3003,
    "category": "OB",
    "topic": "relief",
    "difficulty": 2,
    "question": "OB 말뚝이 스윙에 방해돼요. 뽑아도 될까요?",
    "answers": [
      "고정된 경계 표시는 임의로 뽑지 않아요",
      "샷을 친 뒤 다시 꽂으면 항상 괜찮아요"
    ],
    "correct": 0,
    "explanation": "OB 경계를 표시하는 말뚝을 마음대로 제거해 조건을 바꾸지 않아요."
  },
  {
    "id": "db-3007",
    "sourceId": 3007,
    "sourceRow": 3008,
    "category": "OB",
    "topic": "relief",
    "difficulty": 3,
    "question": "공의 일부가 OB 경계 안에 걸쳐 있어요.",
    "answers": [
      "공 전체가 경계 밖인지 확인해요",
      "조금이라도 밖에 닿으면 무조건 OB예요"
    ],
    "correct": 0,
    "explanation": "OB는 공 전체가 경계 밖에 있는지 판단해요. 경계선의 기준도 함께 확인해요."
  }
];
